USE master
CREATE DATABASE [AUTH] ON PRIMARY (
	NAME = N'PRM001_F001',
	FILENAME = N'C:\SDBF\AUTH\DAT\PRIDAT001_F001.MDF')
LOG ON (
	NAME = N'LOG001_F001',
	FILENAME = N'C:\SDBF\AUTH\LOG\LOG_F001.LDF');
GO

ALTER DATABASE [AUTH] SET COMPATIBILITY_LEVEL = 150;
GO

ALTER DATABASE [AUTH] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT
GO

ALTER DATABASE [AdventureWorks] SET AUTO_CLOSE OFF;
GO

USE AUTH

ALTER DATABASE [AUTH] ADD FILEGROUP COMDAT001;
ALTER DATABASE [AUTH] ADD FILEGROUP COMIDX001;
GO

ALTER DATABASE [AUTH]   
ADD FILE   
(  
    NAME = COMDAT001_F001,  
    FILENAME = N'C:\SDBF\AUTH\DAT\COMDAT001_F001.NDF',  
    SIZE = 1MB,  
    MAXSIZE = Unlimited,  
    FILEGROWTH = 1MB  
),  
(  
    NAME = COMDAT001_F002,  
    FILENAME = N'C:\SDBF\AUTH\DAT\COMDAT001_F002.NDF',  
    SIZE = 1MB,  
    MAXSIZE = Unlimited,  
    FILEGROWTH = 1MB 
)  
TO FILEGROUP COMDAT001;  
GO

ALTER DATABASE [AUTH]   
ADD FILE   
(  
    NAME = COMIDX001_F001,  
    FILENAME = N'C:\SDBF\AUTH\IDX\COMIDX001_F001.NDF',  
    SIZE = 1MB,  
    MAXSIZE = Unlimited,  
    FILEGROWTH = 1MB  
),  
(  
    NAME = COMIDX001_F002,  
    FILENAME = N'C:\SDBF\AUTH\IDX\COMIDX001_F002.NDF',  
    SIZE = 1MB,  
    MAXSIZE = Unlimited,  
    FILEGROWTH = 1MB 
)  
TO FILEGROUP COMIDX001;  
GO
ALTER DATABASE [AUTH] MODIFY FILEGROUP [COMDAT001] DEFAULT
GO